---
# role: ansible-role-nginx
# file: molecule/default/molecule.yml

dependency:
  name: galaxy
  options:
    requirements-file: meta/requirements.yml
driver:
  name: podman
lint: |
  set -e
  ansible-lint
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
    ssh_connection:
      pipelining: true
  log: true
  playbooks:
    converge: ../resources/playbooks/converge.yml
    verify: ../resources/playbooks/verify.yml
verifier:
  name: ansible
platforms:
  - name: debian-11-nginx
    image: "docker.io/jam82/molecule-debian:11"
    pre_build_image: true
  - name: debian-12-nginx
    image: "docker.io/jam82/molecule-debian:12"
    pre_build_image: true
  - name: debian-latest-nginx
    image: "docker.io/jam82/molecule-debian:latest"
    pre_build_image: true
  - name: debian-testing-nginx
    image: "docker.io/jam82/molecule-debian:testing"
    pre_build_image: true
  - name: ubuntu-20.04-nginx
    image: "docker.io/jam82/molecule-ubuntu:20.04"
    pre_build_image: true
  - name: ubuntu-22.04-nginx
    image: "docker.io/jam82/molecule-ubuntu:22.04"
    pre_build_image: true
  - name: ubuntu-latest-nginx
    image: "docker.io/jam82/molecule-ubuntu:latest"
    pre_build_image: true
  - name: almalinux-8-nginx
    image: "docker.io/jam82/molecule-almalinux:8"
    pre_build_image: true
  - name: almalinux-9-nginx
    image: "docker.io/jam82/molecule-almalinux:9"
    pre_build_image: true
  - name: almalinux-latest-nginx
    image: "docker.io/jam82/molecule-almalinux:latest"
    pre_build_image: true
  - name: fedora-39-nginx
    image: "docker.io/jam82/molecule-fedora:39"
    pre_build_image: true
  - name: fedora-latest-nginx
    image: "docker.io/jam82/molecule-fedora:latest"
    pre_build_image: true
  - name: fedora-rawhide-nginx
    image: "docker.io/jam82/molecule-fedora:rawhide"
    pre_build_image: true
